[package]
name = "htos"
version = "0.1.0"
authors = ["totsugeki"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cty = "0.2.1"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
